// @scriptreel/db — postgres.js client, generated types, and queries.
// Phase 1+ populates this. `Database` is regenerated by `pnpm db:types` once
// migrations exist; the placeholder below keeps the package type-checkable now.
export type { Database } from './types';
